"""users table

Revision ID: 530aab4cf4c5
Revises: 28d106131373
Create Date: 2018-05-05 18:17:42.208624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530aab4cf4c5'
down_revision = '28d106131373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
